name: CMake Build

on:
  push:
    branches: [ "main", "devel", "feature/*" ]
  pull_request:
    branches: [ "main", "devel", "feature/*" ]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: 'recursive'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make

      - name: Check compiler version
        run: |
          g++ --version

      - name: Configure CMake with C++23
        run: |
          cmake -S . -B build \
            -DCMAKE_CXX_STANDARD=23 \
            -DCMAKE_CXX_STANDARD_REQUIRED=ON \
            -DBUILD_EXAMPLES=ON

      - name: Build
        run: cmake --build build --parallel
